# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: my-ingress
#   namespace: lrc-portfolio
#   annotations:
#      kubernetes.io/ingress.class: nginx
# spec:
#   rules:
#   - host: lrc-portfolio.35.222.52.217.xip.io
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: lrc-portfolio-service
#           servicePort: 3000