apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "lrc-portfolio.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "lrc-portfolio.labels" . | nindent 4 }}