nameOverride: lrc-portfolio
namespace: lrc-portfolio
serviceAccount:
  name: lrc-portfolio-reader

# Deployment settings
spec:
  replicas: 1
  restartPolicy: Always
  containerPort: 3000
  image:
    repository: lclemons
    tag: lrc-portfolio:1.0.1

# Service settings
service:
  portName: http
  type: ClusterIP
  port: 3000
  targetPort: 80