apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    version: 3.25.0
    name: ingress-nginx